const translations = {
  en: {
    title: "Join GramCart",
    seller: "I'm a Seller",
    sellerDesc: "Farmer/Artisan",
    buyer: "I'm a Buyer",
    buyerDesc: "Individual/Business",
    phoneLabel: "Phone Number",
    phonePlaceholder: "Enter phone number",
    sendOTP: "Send OTP",
    otpLabel: "Enter OTP",
    createAccount: "Create Account",
    haveAccount: "Already have an account?",
    signIn: "Sign in",
    nameLabel: "Name",
    addressLabel: "Address",
    passwordLabel: "Password",
    namePlaceholder: "Enter your name",
    addressPlaceholder: "Enter full address",
    passwordPlaceholder: "Create password",
    resendOTP: "Resend OTP",
    invalidPhone: "Invalid phone number",
    invalidEmail: "Invalid email address",
    weakPassword: "Password must be at least 6 characters",
    otpInvalid: "Please enter 6-digit OTP",
  },
  hi: {
    title: "ग्रामीणकार्ट से जुड़ें",
    seller: "मैं विक्रेता हूँ",
    sellerDesc: "किसान/कारीगर",
    buyer: "मैं खरीदार हूँ",
    buyerDesc: "व्यक्ति/व्यवसाय",
    phoneLabel: "फ़ोन नंबर",
    phonePlaceholder: "फ़ोन नंबर दर्ज करें",
    sendOTP: "ओटीपी भेजें",
    otpLabel: "ओटीपी दर्ज करें",
    createAccount: "खाता बनाएं",
    haveAccount: "पहले से खाता है?",
    signIn: "लॉग इन करें",
    nameLabel: "नाम",
    addressLabel: "पता",
    passwordLabel: "पासवर्ड",
    namePlaceholder: "अपना नाम दर्ज करें",
    addressPlaceholder: "पता दर्ज करें",
    passwordPlaceholder: "पासवर्ड बनाएं",
    resendOTP: "ओटीपी फिर से भेजें",
    invalidPhone: "अमान्य फ़ोन नंबर",
    invalidEmail: "अमान्य ईमेल पता",
    weakPassword: "पासवर्ड कम से कम 6 वर्णों का होना चाहिए",
    otpInvalid: "कृपया 6-अंक का ओटीपी दर्ज करें"
  },
  ta: {
    title: "கிராமக்கார்ட் சேரவும்",
    seller: "நான் விற்பனையாளர்",
    sellerDesc: "விவசாயி/கலைஞர்",
    buyer: "நான் வாங்குபவர்",
    buyerDesc: "தனிநபர்/வணிகம்",
    phoneLabel: "தொலைபேசி எண்",
    phonePlaceholder: "தொலைபேசி எண்ணை உள்ளிடவும்",
    sendOTP: "ஓடிபி அனுப்பவும்",
    otpLabel: "ஓடிபி உள்ளிடவும்",
    createAccount: "கணக்கை உருவாக்கவும்",
    haveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    signIn: "உள்நுழைக",
    nameLabel: "பெயர்",
    addressLabel: "முகவரி",
    passwordLabel: "கடவுச்சொல்",
    namePlaceholder: "உங்கள் பெயரை உள்ளிடவும்",
    addressPlaceholder: "முழு முகவரியை உள்ளிடவும்",
    passwordPlaceholder: "கடவுச்சொல்லை உருவாக்கவும்",
    resendOTP: "ஓடிபி மீண்டும் அனுப்பவும்",
    invalidPhone: "தவறான தொலைபேசி எண்",
    invalidEmail: "தவறான மின்னஞ்சல் முகவரி",
    weakPassword: "கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்",
    otpInvalid: "6-எண் ஓடிபியை உள்ளிடவும்"
  },
  ml: {
    title: "ഗ്രാമകാര്‍ട്ടില്‍ ചേരുക",
    seller: "ഞാന്‍ വില്‍പനക്കാരന്‍ ആണ്",
    sellerDesc: "കർഷകൻ/കലാകാരൻ",
    buyer: "ഞാന്‍ വാങ്ങുന്നവന്‍ ആണ്",
    buyerDesc: "വ്യക്തിഗതം/ബിസിനസ്സ്",
    phoneLabel: "ഫോൺ നമ്പർ",
    phonePlaceholder: "ഫോൺ നമ്പർ നൽകുക",
    sendOTP: "ഒടിപി അയയ്ക്കുക",
    otpLabel: "ഒടിപി നൽകുക",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    haveAccount: "ഇതിനുമുമ്പ് അക്കൗണ്ട് ഉണ്ടോ?",
    signIn: "ലോഗിൻ ചെയ്യുക",
    nameLabel: "പേര്",
    addressLabel: "വിലാസം",
    passwordLabel: "പാസ്വേഡ്",
    namePlaceholder: "പേര് നൽകുക",
    addressPlaceholder: "മുഴുവൻ വിലാസം നൽകുക",
    passwordPlaceholder: "പാസ്വേഡ് സൃഷ്ടിക്കുക",
    resendOTP: "ഒടിപി വീണ്ടും അയയ്ക്കുക",
    invalidPhone: "തെറ്റായ ഫോൺ നമ്പർ",
    invalidEmail: "തെറ്റായ ഇമെയിൽ വിലാസം",
    weakPassword: "പാസ്വേഡ് കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ ആയിരിക്കണം",
    otpInvalid: "6-അക്കം ഒടിപി നൽകുക"
  }
};